version: "2"
linters:
  enable:
    - errorlint
    - exhaustive
    - goconst
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
  settings:
    exhaustive:
      default-signifies-exhaustive: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
